#!/usr/bin/env lua

local base_dir = os.getenv("HOME") .. "/.xtorrent"

package.path = package.path .. ";" .. base_dir .. "/?.lua;" .. base_dir .. "/.modules/share/lua/5.4/?.lua;"
package.cpath = package.cpath .. ";" .. base_dir .. "/.modules/lib/lua/5.4/?.so"

local utils = require("utils")

local arg_count = #arg

io.write([[

###Torrent cli###

]])

if arg_count > 0 then
	local prefix = arg[1]

	if prefix == "-s" then
		local query = arg[2]
		local search = "?q=" .. query
		local res = utils.fetchTorrent(search)
		utils.torrentOptions(res)
	end
else
	io.write([[
Enter 1 for Movies
Enter 2 for Music
Enter 3 for E-books
Enter 4 for Other
]])

	local reply = utils.readInput()

	if reply ~= nil then
		local iReply = tonumber(reply)
		local categories = { "201", "208", "601", "699" }

		local categoryId = categories[iReply]
		local url = "?q=category:" .. "" .. categoryId
		local res = utils.fetchTorrent(url)
		utils.torrentOptions(res)
	end
end
